[tool.poetry]
name = "2022"
version = "0.1.0"
description = "Advent of Code 2022"
authors = ["bassil"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
